# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aliskanlikguncel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_aliskanlik = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_aliskanlik.setGeometry(QtCore.QRect(95, 31, 611, 471))
        self.tableWidget_aliskanlik.setObjectName("tableWidget_aliskanlik")
        self.tableWidget_aliskanlik.setColumnCount(0)
        self.tableWidget_aliskanlik.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(84, 510, 81, 20))
        self.label.setObjectName("label")
        self.lineEdit_aliskanlik = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_aliskanlik.setGeometry(QtCore.QRect(180, 510, 113, 22))
        self.lineEdit_aliskanlik.setObjectName("lineEdit_aliskanlik")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 510, 55, 16))
        self.label_2.setObjectName("label_2")
        self.dateEdit_tarih = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_tarih.setGeometry(QtCore.QRect(510, 510, 110, 22))
        self.dateEdit_tarih.setObjectName("dateEdit_tarih")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 510, 55, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(370, 510, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_kaydet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_kaydet.setGeometry(QtCore.QRect(330, 540, 93, 28))
        self.pushButton_kaydet.setObjectName("pushButton_kaydet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Alışkanlık adı:"))
        self.label_2.setText(_translate("MainWindow", "Tarih:"))
        self.label_3.setText(_translate("MainWindow", "Durum:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "tamamlandı"))
        self.comboBox.setItemText(1, _translate("MainWindow", "tamamlanmadı"))
        self.pushButton_kaydet.setText(_translate("MainWindow", "Kaydet"))
