# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_anakeran = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_anakeran.setGeometry(QtCore.QRect(125, 41, 551, 451))
        self.tableWidget_anakeran.setStyleSheet("background-color: #d8b9ff;\n"
"")
        self.tableWidget_anakeran.setObjectName("tableWidget_anakeran")
        self.tableWidget_anakeran.setColumnCount(0)
        self.tableWidget_anakeran.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 70, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_aliskanlik = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_aliskanlik.setGeometry(QtCore.QRect(320, 220, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_aliskanlik.setFont(font)
        self.pushButton_aliskanlik.setObjectName("pushButton_aliskanlik")
        self.pushButton_duygugunluk = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_duygugunluk.setGeometry(QtCore.QRect(310, 270, 111, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_duygugunluk.setFont(font)
        self.pushButton_duygugunluk.setObjectName("pushButton_duygugunluk")
        self.pushButton_cikis = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cikis.setGeometry(QtCore.QRect(320, 320, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cikis.setFont(font)
        self.pushButton_cikis.setObjectName("pushButton_cikis")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 130, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Zihin Bahçesine Hoşgeldiniz..."))
        self.pushButton_aliskanlik.setText(_translate("MainWindow", "Alışkanlıklar"))
        self.pushButton_duygugunluk.setText(_translate("MainWindow", "Duygu Günlüğü"))
        self.pushButton_cikis.setText(_translate("MainWindow", "Çıkış"))
        self.label_2.setText(_translate("MainWindow", "Zihninizin derinliklerine doğru bir yolculuğa çıkmaya hazır mısınız?"))
