# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'duygugunlugugüncel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 736)
        MainWindow.setStyleSheet("background-color: #F0F8FF;\n"
"``\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_duygular = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_duygular.setGeometry(QtCore.QRect(70, 30, 631, 471))
        self.tableWidget_duygular.setStyleSheet("background-color: #E6E6FA;\n"
"")
        self.tableWidget_duygular.setObjectName("tableWidget_duygular")
        self.tableWidget_duygular.setColumnCount(0)
        self.tableWidget_duygular.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 530, 55, 16))
        self.label.setObjectName("label")
        self.dateEdit_tarihDuygu = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_tarihDuygu.setGeometry(QtCore.QRect(60, 530, 110, 22))
        self.dateEdit_tarihDuygu.setStyleSheet("background-color: #E6E6FA;\n"
"")
        self.dateEdit_tarihDuygu.setObjectName("dateEdit_tarihDuygu")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(184, 530, 61, 20))
        self.label_2.setObjectName("label_2")
        self.comboBox_duygu = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_duygu.setGeometry(QtCore.QRect(260, 530, 73, 22))
        self.comboBox_duygu.setStyleSheet("background-color: #E6E6FA;\n"
"")
        self.comboBox_duygu.setObjectName("comboBox_duygu")
        self.comboBox_duygu.addItem("")
        self.comboBox_duygu.addItem("")
        self.comboBox_duygu.addItem("")
        self.comboBox_duygu.addItem("")
        self.comboBox_duygu.addItem("")
        self.comboBox_duygu.addItem("")
        self.comboBox_duygu.addItem("")
        self.comboBox_duygu.addItem("")
        self.textEdit_notlar = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_notlar.setGeometry(QtCore.QRect(420, 520, 201, 151))
        self.textEdit_notlar.setStyleSheet("background-color: #E6E6FA;\n"
"")
        self.textEdit_notlar.setObjectName("textEdit_notlar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 530, 55, 16))
        self.label_3.setObjectName("label_3")
        self.pushButtonkaydetDuygu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonkaydetDuygu.setGeometry(QtCore.QRect(170, 600, 93, 28))
        self.pushButtonkaydetDuygu.setStyleSheet("background-color: #E6E6FA;\n"
"")
        self.pushButtonkaydetDuygu.setObjectName("pushButtonkaydetDuygu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tarih:"))
        self.label_2.setText(_translate("MainWindow", "Duygular:"))
        self.comboBox_duygu.setItemText(0, _translate("MainWindow", "Endişeli"))
        self.comboBox_duygu.setItemText(1, _translate("MainWindow", "Mutlu"))
        self.comboBox_duygu.setItemText(2, _translate("MainWindow", "Üzgün"))
        self.comboBox_duygu.setItemText(3, _translate("MainWindow", "Heyecanlı"))
        self.comboBox_duygu.setItemText(4, _translate("MainWindow", "Şaşkın"))
        self.comboBox_duygu.setItemText(5, _translate("MainWindow", "Huzurlu"))
        self.comboBox_duygu.setItemText(6, _translate("MainWindow", "Kızgın"))
        self.comboBox_duygu.setItemText(7, _translate("MainWindow", "Depresif"))
        self.label_3.setText(_translate("MainWindow", "Notlar"))
        self.pushButtonkaydetDuygu.setText(_translate("MainWindow", "Kaydet"))
