# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'girisekrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_giris = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_giris.setGeometry(QtCore.QRect(120, 50, 511, 431))
        self.tableWidget_giris.setStyleSheet("background-color: #d8b9ff;\n"
"")
        self.tableWidget_giris.setObjectName("tableWidget_giris")
        self.tableWidget_giris.setColumnCount(0)
        self.tableWidget_giris.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 70, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(190, 150, 171, 22))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 220, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_sifre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sifre.setGeometry(QtCore.QRect(190, 250, 171, 22))
        self.lineEdit_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")
        self.pushButton_kayitol = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_kayitol.setGeometry(QtCore.QRect(160, 340, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_kayitol.setFont(font)
        self.pushButton_kayitol.setObjectName("pushButton_kayitol")
        self.pushButton_girisyap = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_girisyap.setGeometry(QtCore.QRect(280, 340, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_girisyap.setFont(font)
        self.pushButton_girisyap.setObjectName("pushButton_girisyap")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Zihin Bahçesine Giriş Yapın"))
        self.label_2.setText(_translate("MainWindow", "Email:"))
        self.label_3.setText(_translate("MainWindow", "Şifre:"))
        self.pushButton_kayitol.setText(_translate("MainWindow", "Kayıt Ol"))
        self.pushButton_girisyap.setText(_translate("MainWindow", "Giriş Yap"))
